"""add_uploaded_by_id_to_document

Revision ID: 1ea42509a007
Revises: b866d6aca145
Create Date: 2026-08-08 04:56:07.554407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ea42509a007'
down_revision = 'b866d6aca145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('uploaded_by_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_document_uploaded_by_id'), 'document', ['uploaded_by_id'], unique=False)
    op.create_foreign_key(None, 'document', 'user', ['uploaded_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_uploaded_by_id_fkey', 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_uploaded_by_id'), table_name='document')
    op.drop_column('document', 'uploaded_by_id')
    # ### end Alembic commands ###
