"""replace_item_with_prd_schema

Revision ID: 38e492099cb9
Revises: fe56fa70289e
Create Date: 2026-08-01 13:34:59.447021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38e492099cb9'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cited_insight_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_project_id'), 'chatmessage', ['project_id'], unique=False)
    op.create_table('document',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'docx', 'txt', name='documentformat'), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processingstatus'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_project_id'), 'document', ['project_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='reportstatus'), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('insight_count_at_generation', sa.Integer(), nullable=True),
    sa.Column('reviewed_count_at_generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_project_id'), 'report', ['project_id'], unique=False)
    op.create_table('participant',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('age_range', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('segment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code', 'document_id', name='uq_participant_refcode_document')
    )
    op.create_index(op.f('ix_participant_document_id'), 'participant', ['document_id'], unique=False)
    op.create_table('insight',
    sa.Column('type', sa.Enum('pain_point', 'opportunity', 'feature_request', 'quote', 'jtbd', name='insighttype'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_quote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='sentiment'), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('unreviewed', 'confirmed', 'edited', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rejection_reason', sa.Enum('wrong_type', 'wrong_quote', 'not_an_insight', name='rejectionreason'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_document_id'), 'insight', ['document_id'], unique=False)
    op.create_index(op.f('ix_insight_project_id'), 'insight', ['project_id'], unique=False)
    op.drop_table('item')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_index(op.f('ix_insight_project_id'), table_name='insight')
    op.drop_index(op.f('ix_insight_document_id'), table_name='insight')
    op.drop_table('insight')
    op.drop_index(op.f('ix_participant_document_id'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_report_project_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_document_project_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_chatmessage_project_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_table('project')

    op.execute("DROP TYPE IF EXISTS reportstatus")
    op.execute("DROP TYPE IF EXISTS chatrole")
    op.execute("DROP TYPE IF EXISTS rejectionreason")
    op.execute("DROP TYPE IF EXISTS reviewstatus")
    op.execute("DROP TYPE IF EXISTS sentiment")
    op.execute("DROP TYPE IF EXISTS insighttype")
    op.execute("DROP TYPE IF EXISTS documentformat")
    op.execute("DROP TYPE IF EXISTS processingstatus")
    # ### end Alembic commands ###
