"""cascade_delete_insights_with_document

Revision ID: 8929621d9ab7
Revises: 1ea42509a007
Create Date: 2026-08-13 13:23:12.714244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8929621d9ab7'
down_revision = '1ea42509a007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insight_document_id_fkey'), 'insight', type_='foreignkey')
    op.create_foreign_key(None, 'insight', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint('insight_document_id_fkey', 'insight', type_='foreignkey')
    op.create_foreign_key(
        'insight_document_id_fkey',
        'insight',
        'document',
        ['document_id'],
        ['id'],
        ondelete='SET NULL',
    )