"""add_is_archived_to_project

Revision ID: b866d6aca145
Revises: 38e492099cb9
Create Date: 2026-08-07 05:05:18.213457

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b866d6aca145'
down_revision = '38e492099cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_archived')
    # ### end Alembic commands ###
